services:
  app:
    image: node:18-alpine
    depends_on:
      - db
    working_dir: /todo
    volumes:
      - ./:/todo
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./src/db/:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

