import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <p>This is /layout.tsx. It contains a React component called RootLayout() which is rendering this page. Neat huh?</p>
        <p>The RootLayhout() component takes a property called 'children' which are called after this paragraph</p>
        <br />
        {children}
      </body>
    </html>
  )
}
